version: '3.8'

services:
  browser-use-webui:
    container_name: browser-use-webui
    image: your-image-name:latest  # Or use a working base image like "browsergpt/browsergpt"
    platform: linux/amd64
    ports:
      - "7788:7788"  # Web UI (e.g., Gradio)
      - "6080:6080"  # noVNC WebSocket UI
      - "5901:5901"  # VNC server port
      - "9222:9222"  # Chrome Remote Debugging
    environment:
      - DISPLAY=:1
      - RESOLUTION=1920x1080x24
      - VNC_PASSWORD=vncpassword
      - CHROME_PATH=/usr/bin/google-chrome
      - CHROME_CDP=http://localhost:9222
      - CHROME_USER_DATA=/app/data/chrome_data
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /tmp
    command: >
      bash -c "
      Xvfb :1 -screen 0 1920x1080x24 & 
      sleep 2 &&
      x11vnc -display :1 -forever -nopw -shared -rfbport 5901 &
      websockify --web=/usr/share/novnc/ 6080 localhost:5901 &
      python3 app.py
      "